const categories = [
  { name: "Electronics", href: "/category/electronics" },
  { name: "Computers & Accessories", href: "/category/computers-accessories" },
  { name: "Mobile Phones & Accessories", href: "/category/mobile-phones-accessories" },
  { name: "Fashion", href: "/category/fashion" },
  { name: "Men's Clothing", href: "/category/mens-clothing" },
  { name: "Women's Clothing", href: "/category/womens-clothing" },
  { name: "Kid's Clothing", href: "/category/kids-clothing" },
  { name: "Shoes & Footwear", href: "/category/shoes-footwear" },
  { name: "Bags & Luggage", href: "/category/bags-luggage" },
  { name: "Watches & Jewelry", href: "/category/watches-jewelry" },
  { name: "Beauty & Personal Care", href: "/category/beauty-personal-care" },
  { name: "Health & Wellness", href: "/category/health-wellness" },
  { name: "Home & Living", href: "/category/home-living" },
  { name: "Furniture", href: "/category/furniture" },
  { name: "Kitchen & Dining", href: "/category/kitchen-dining" },
  { name: "Home Decor", href: "/category/home-decor" },
  { name: "Bedding & Bath", href: "/category/bedding-bath" },
  { name: "Groceries", href: "/category/groceries" },
  { name: "Food & Beverages", href: "/category/food-beverages" },
  { name: "Snacks", href: "/category/snacks" },
  { name: "Baby Products", href: "/category/baby-products" },
  { name: "Toys & Games", href: "/category/toys-games" },
  { name: "Books & Stationery", href: "/category/books-stationery" },
  { name: "Automotive Tools", href: "/category/automotive-tools" },
  { name: "Car Accessories", href: "/category/car-accessories" },
  { name: "Motorcycle Accessories", href: "/category/motorcycle-accessories" },
  { name: "Tools & Home Improvement", href: "/category/tools-home-improvement" },
  { name: "Carpenter Tools", href: "/category/carpenter-tools" },
  { name: "Plumber Tools", href: "/category/plumber-tools" },
  { name: "Mason Tools", href: "/category/mason-tools" },
  { name: "Painter Tools", href: "/category/painter-tools" },
  { name: "Garden & Outdoor", href: "/category/garden-outdoor" },
  { name: "Pet Supplies", href: "/category/pet-supplies" },
  { name: "Sports & Outdoors", href: "/category/sports-outdoors" },
  { name: "Fitness & Exercise", href: "/category/fitness-exercise" },
  { name: "Musical Instruments", href: "/category/musical-instruments" },
  { name: "Gaming", href: "/category/gaming" },
  { name: "Software", href: "/category/software" },
  { name: "Office Supplies", href: "/category/office-supplies" },
  { name: "Industrial Equipment", href: "/category/industrial-equipment" },
  { name: "Art & Craft Supplies", href: "/category/art-craft-supplies" },
  { name: "Others", href: "/category/others" }
];

export default categories;

export  const govermentId = [
  {names: "Driver's Licence"},
  {names: "Passport"},
  {names: "National Id"},
  {names: "Police Clearance"},
  {names: "NBI Clearance"},
];
